version: '3.1'
volumes:
  data:
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MYSQL_DATABASE: vaccinelocation
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3309:3306"

